# Generated by Django 5.0.6 on 2024-07-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_vaccinerecord_attending_physician_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinerecord',
            name='vaccine_venue',
            field=models.CharField(default='Johnson & Johnson', max_length=100),
        ),
    ]
