# Generated by Django 5.0.6 on 2024-07-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinerecord',
            name='attending_physician_first_name',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='vaccinerecord',
            name='attending_physician_last_name',
            field=models.CharField(default='Doe', max_length=100),
        ),
    ]
