# Generated by Django 5.0.6 on 2024-07-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_vaccinerecord_vaccine_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinerecord',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinerecord',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('under review', 'Under Review'), ('rejected', 'Rejected')], default='Under Review', max_length=20),
        ),
    ]
