# Generated by Django 5.0.6 on 2024-07-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_vaccinerecord_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinerecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
